# Generated by Django 3.0.5 on 2020-04-23 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_auto_20200422_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('men', 'Men.'), ('women', 'Women.'), ('sale', 'Sale'), ('stain', 'Stain Repellent'), ('aOdor', 'Anti Odor'), ('upper', 'Upper Wear'), ('bottom', 'Bottom Wear'), ('winter', 'Winter Collection'), ('summer', 'Summer Collection'), ('spring', 'Spring Collection'), ('autumn', 'Autumn Collection'), ('none', 'None')], default='none', max_length=50),
        ),
    ]
