# Generated by Django 3.0.5 on 2020-04-23 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0006_auto_20200423_0633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.TextField(default='none', help_text='men women stain odor upper bottom', verbose_name='Add Categories'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.FloatField(blank=True, help_text="Leave Blank If there's no discount"),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.CharField(help_text="Write all the tags Separated by ',' comma", max_length=100),
        ),
    ]
