# Generated by Django 3.0.5 on 2020-04-23 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0007_auto_20200423_0658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=3)),
                ('color', models.CharField(max_length=10)),
                ('quantity', models.SmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, help_text='Separate with comma Select from following: men, women, stain-repellent, anti-odor, upper, bottom, spring-collection, summer-collection, winter-collection, autumn-collection', max_length=300, verbose_name='Add Categories'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(to='Guest.Variant'),
        ),
    ]
