# Generated by Django 3.0.3 on 2020-05-07 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0017_inventory_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.SmallIntegerField(default=100),
        ),
    ]
