# Generated by Django 3.0.3 on 2020-05-07 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0018_auto_20200508_0432'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InventoryManager',
        ),
    ]
