# Generated by Django 3.0.3 on 2020-05-08 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0019_delete_inventorymanager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='notes',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variation',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='Guest.Inventory'),
        ),
    ]
