# Generated by Django 3.0.3 on 2020-05-08 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0023_auto_20200508_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='total',
            field=models.DecimalField(decimal_places=2, default=4, max_digits=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='Guest.Customer'),
            preserve_default=False,
        ),
    ]
