# Generated by Django 3.0.5 on 2020-04-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0003_order_product_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sec_imgs',
        ),
        migrations.AddField(
            model_name='product',
            name='fourth_img',
            field=models.ImageField(blank=True, upload_to='product/sec_images'),
        ),
        migrations.AddField(
            model_name='product',
            name='sec_img',
            field=models.ImageField(blank=True, upload_to='product/sec_images'),
        ),
        migrations.AddField(
            model_name='product',
            name='third_img',
            field=models.ImageField(blank=True, upload_to='product/sec_images'),
        ),
    ]
