# Generated by Django 3.0.5 on 2020-04-23 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=50, verbose_name='Add New Category Type')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AlterField(
            model_name='product',
            name='main_img',
            field=models.ImageField(upload_to='product/main_images', verbose_name='Product Main Image'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='Guest.CategoryChoices', verbose_name='Select Categories'),
        ),
    ]
