# Generated by Django 3.0.5 on 2020-04-27 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0011_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
