# Generated by Django 3.0.5 on 2020-04-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0011_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
