# Generated by Django 2.2.10 on 2020-04-27 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0015_auto_20200428_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_no',
            field=models.CharField(default=34327, max_length=100),
        ),
    ]
