# Generated by Django 3.0.3 on 2020-05-07 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0015_auto_20200508_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
