# Generated by Django 3.0.5 on 2020-05-08 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0020_auto_20200508_0543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='variation',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(to='Guest.Inventory'),
        ),
    ]
