# Generated by Django 3.0.5 on 2020-05-08 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0022_auto_20200508_0620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='active',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.SmallIntegerField(),
        ),
    ]
