# Generated by Django 3.0.3 on 2020-05-08 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0022_auto_20200508_0620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='order_time',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='product',
        ),
        migrations.AddField(
            model_name='orders',
            name='cart',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='Guest.Cart'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='order_id',
            field=models.CharField(default='PRESTIGE666', max_length=120, unique=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
